### ISSUE TITLE
Issues with new airbnb-eslint

### ISSUE THREAD

**Issue by Jakedavies** [strawhouselabs/eslint-config-strawhouse#5]
Discussion for changes we dont like in the new airbnb eslint

**Comment by Jakedavies** [comment]
We have decided we don't like the new comma dangle, proposed change is:

```
'comma-dangle': ['error', {
  functions: 'never'
}],
```

The current rule forces us to use babel to achieve what it wants.

**Comment by jakeorr** [comment]
Airbnb is defaulting to require `.jsx` file extension if the file contains JSX. This rule will accept either extension:

```json
"react/jsx-filename-extension": ["error", { "extensions": [".js", ".jsx"] }]
```

**Comment by jakeorr** [comment]
Any thoughts on this rule? https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-static-element-interactions.md

We use `<li>` elements for interactions in lots of spots. I would consider turning this off, but does anyone have any opposition?

*update:*
I immediately found this thread about using the aforementioned rule: https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/91

The accessibility issues (i.e. having a tab index on interactive elements) seem legitimate to me. Perhaps these are worth updating. @gburtini @Jakedavies @CodyReeves any opinions?

*update 2:*
example of us using an `<li>` as an interactive element https://github.com/strawhouselabs/dashboard2/blob/c67b2cd32a0360152f3ed229969a036690f3e8cd/src/assets/js/app/components/details_card.js#L292-L294

**Comment by gburtini** [comment]
***The below is wrong for the reason expressed in the update above.*** I'm an idiot don't mind me.

I think the reason they have this is for backwards/fallback compatibility perhaps with a bit of a "semantic HTML" bent, but being a SPA there is no such thing anyway. 

I am not opposed to disabling this rule. Semantic use of HTML elements/clean markup is very dead in React applications.

**Edit:** my revised opinion is to keep the rule and update the li usage to be <a class='list-item' or something where .list-item provides `display:list-item`. This provides better usability and meets the lint rule while only coming at a cost of semantic HTML.

**Comment by jakeorr** [comment]
Added rules in https://github.com/strawhouselabs/eslint-config-strawhouse/commit/b6df7b49fe0beee6e1774b8daa58b0d165c0e163
